environment:
  matrix:
    - PYTHON_VERSION: 2.7
      MINICONDA: C:\Miniconda
    - PYTHON_VERSION: 3.6
      MINICONDA: C:\Miniconda3
init:
  - "ECHO %PYTHON_VERSION% %MINICONDA%"

install:
  - "set PATH=%MINICONDA%;%MINICONDA%\\Scripts;%PATH%"
  - conda config --set always_yes yes --set changeps1 no
  - conda update -q conda
  - conda info -a
  - "conda create -q -n test-environment python=%PYTHON_VERSION% numpy"

  # Install dependencies
  - activate test-environment
  - conda install -c conda-forge pyside
  - conda install -c conda-forge pyinstaller
 
  # Check to see that I have the correct version of Python
  - "python --version"
  
  # Add to path the current folder
  - "SET PYTHONPATH=%PYTHONPATH%;%CD%"

  # Install SHARPpy
  - "python setup.py install"

