env:
  global:
    # sharppy-docs-bot GH
    secure: "cZ8a+Y0Tet+nFveZiypiHNXzDEATr6hQ7ZYNv255Kuk4ejSoai1cyRgxRsec+5agqvEw/O9fsbG2uxt5ELOFf0Uog0TypCCcI2bwwxXhb1SXO0GEn2dVwx6USABXPgsZi4a5dK48vNLEWlR5lPtRQYexfWGuVJSw8STYqjN6yREwYELW1dCCSFnJBCTBAXnUsx8w0ps43ruNflt2u6lTEr8G5g2wUOsVOCkZ97AMOncL2BybeLGyxMJydfNhtl04pEcfP57QNbEuZ52IEWDp6g2Hx0btsIp+i/v26Ycqir+A5z0Op5U3cGam/7ZSdSMFzFW+2Yq8fifIQbaQJnVss6BPPZSaErHjiyDBpBOXovqnf6IzJT1YLOvPqqdA1d3bX3LzSF6AuLy6rZ5LbuiZeap7tsxSP87y7n7lyELWUd9+u0jWm2jc7RWBrJeNVOom74HEGXM+bxg8PcZLHIFuwkw3pyw4dCswjOImtkCu09xOE/u7GAPrAYzXRzr1z/KPuP5amteoIUUdXGg0TZBysIuyeM2GOLW+D4KL2KTrDD91e2Nfw5O3QmojpTPR4NQBNuw05e5Oykq2WGVlPVDb6By4q6FcgVlglTyle7gIs/YPv+THGuE+9iGq09jFVhHIo6nSWohHBAqiIQ0mIRSW86bXvYnmvcng9meIy3Xl6PI="   
matrix:
  include:
  - os: osx
    language: generic
    env: PYTHON_VERSION="2.7"
  - os: osx
    language: generic
    env: PYTHON_VERSION="3.7"
  - os: linux
    language: generic
    env: PYTHON_VERSION="2.7"
  - os: linux
    language: generic
    env: PYTHON_VERSION="3.7"
    env: BUILD_DOCS="YES"
before_install:
- source ci/install.sh
install:
- python setup.py install
script:
- python sharppy/tests/test_url.py http://sharp.weather.ou.edu/soundings/archive/1973/09/19/00/DDC.txt
# If the test script passes, build the binaries.
after_success:
# Zip the binaries, as we can't transfer 
- source ci/build_docs.sh
- source ci/make_binary.sh
before_deploy:
- cd dist
- if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then zip -r SHARPpy-osx.zip SHARPpy.app; else zip -r SHARPpy-linux.zip * ; if
- cd ..
# Ship the binaries to Github
deploy:
  provider: releases
  api_key:
    secure: upm1CAgyi6Qv+KaHAo/v3mDyaXYSFs+vm0qS1D7IUDapGIhOTfqDgOpS71bFAnM9w+FRc7S3foxmymsHZsK97LVOEqHNibBtSmELVzhv2VHoCfAUnHaOzCi/z4DHx3QKn2ALLymFfG4O7XzSC7urHue9/h9DWy51srokafP3QOnI6sWHkWGOOOv0i13MDzv2RxMza7+PT69bQ2vFk2ujwAthanDySeXyf2kJ7WYj1cuEBfASBs+diVUSqk7FxJO7OQhyLCCn5bSS3Otvg9tkHL8H7WU6JoGHLBoUPDUxCl0KePgie6hZvaJFAlhcJfmSA4NsTQfunFnbHa2rPFPUTLO6RgEbtD0Th85VORmmEeJ8O+GmvZIRBZUiMxPAbb1DXPwI6XtgoFhNiV5rkut4JtL3BgRmAfIdAsvBfNbozgRpHAOpoiIzx/8wan+o73h6K1y+qfQwxBw+cJAL3n0A2M3x7/mpALLf3JLD8E5KKLbp/kedPIF2vKXZ92h85H9AkMopHqLHQGj86M0qHbQyMp6OHR2ivG2K9qqtzAaUNglQrUaQOHeaBZ8ZT7+mhpdhaN1w5fmuYPRchVzyNbM3DtdiUfAGc6adZPUaUktbiIpLigjwS6BO4FALngrI9+M+kk8qHv/zukOiGawzueCDUGc79G/8LI7Q1EKkiqyI+3E=
  file_glob: true
  file: dist/SHARPpy*.zip
  skip_cleanup: true
  draft: true
  overwrite: true
  on:
    repo: sharppy/SHARPpy
    tags: true
