matrix:
  include:
  - os: osx
    language: generic
    env: PYTHON_VERSION="2.7"
  - os: osx
    language: generic
    env: PYTHON_VERSION="3.7"
  - os: linux
    language: generic
    env: PYTHON_VERSION="2.7"
  - os: linux
    language: generic
    env: PYTHON_VERSION="3.7"
before_install:
- echo $PYTHON_VERSION
- if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then if [[ "$PYTHON_VERSION" == "2.7" ]]; then
  curl https://repo.continuum.io/miniconda/Miniconda2-latest-MacOSX-x86_64.sh -o miniconda.sh;
  else curl https://repo.continuum.io/miniconda/Miniconda3-latest-MacOSX-x86_64.sh
  -o miniconda.sh; fi else if [[ "$PYTHON_VERSION" == "2.7" ]]; then wget https://repo.continuum.io/miniconda/Miniconda2-latest-Linux-x86_64.sh
  -O miniconda.sh; else wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh
  -O miniconda.sh; fi fi
- bash miniconda.sh -b -p $HOME/miniconda
- export PATH="$HOME/miniconda/bin:$PATH"
- hash -r
- conda config --set always_yes yes --set changeps1 no
- conda update -q conda
- conda info -a
- conda create -q -n test-environment python=$PYTHON_VERSION numpy nose
- source activate test-environment
- conda install -c conda-forge pyside
- conda install -c conda-forge pyinstaller
# If we're building on OSX, we need to download python.app to get around the qt_menu.nib problem.
- if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then conda install python.app; fi
install:
- python setup.py install
script:
- python sharppy/tests/test_url.py http://sharp.weather.ou.edu/soundings/archive/1973/09/19/00/DDC.txt
# If the test script passes, build the binaries.
after_success:
- if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then pyinstaller runsharp/SHARPpy-osx.spec
  --onefile --noconsole; else pyinstaller runsharp/SHARPpy-linux-redhat5.spec; fi
- ls -lht dist/
# Zip the binaries, as we can't transfer .app
before_deploy:
- cd dist
- if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then zip -r SHARPpy-osx.zip SHARPpy.app; else zip -r SHARPpy-linux.zip * ; if
- cd ..
# Ship the binaries to Github
deploy:
  provider: releases
  api_key:
    secure: upm1CAgyi6Qv+KaHAo/v3mDyaXYSFs+vm0qS1D7IUDapGIhOTfqDgOpS71bFAnM9w+FRc7S3foxmymsHZsK97LVOEqHNibBtSmELVzhv2VHoCfAUnHaOzCi/z4DHx3QKn2ALLymFfG4O7XzSC7urHue9/h9DWy51srokafP3QOnI6sWHkWGOOOv0i13MDzv2RxMza7+PT69bQ2vFk2ujwAthanDySeXyf2kJ7WYj1cuEBfASBs+diVUSqk7FxJO7OQhyLCCn5bSS3Otvg9tkHL8H7WU6JoGHLBoUPDUxCl0KePgie6hZvaJFAlhcJfmSA4NsTQfunFnbHa2rPFPUTLO6RgEbtD0Th85VORmmEeJ8O+GmvZIRBZUiMxPAbb1DXPwI6XtgoFhNiV5rkut4JtL3BgRmAfIdAsvBfNbozgRpHAOpoiIzx/8wan+o73h6K1y+qfQwxBw+cJAL3n0A2M3x7/mpALLf3JLD8E5KKLbp/kedPIF2vKXZ92h85H9AkMopHqLHQGj86M0qHbQyMp6OHR2ivG2K9qqtzAaUNglQrUaQOHeaBZ8ZT7+mhpdhaN1w5fmuYPRchVzyNbM3DtdiUfAGc6adZPUaUktbiIpLigjwS6BO4FALngrI9+M+kk8qHv/zukOiGawzueCDUGc79G/8LI7Q1EKkiqyI+3E=
  file_glob: true
  file: dist/SHARPpy*.zip
  skip_cleanup: true
  draft: true
  overwrite: true
  on:
    repo: sharppy/SHARPpy
    tags: true
