name: devel
channels:
  - conda-forge/label/testing
  - conda-forge
dependencies:
  - python=3
  - numpy=1.15.*
  - pyside
  - sphinx
  - sphinx-gallery
  - sphinx-rtd-theme
  - pytest
  - pip:
    - sphinx-prompt
    - pydocstyle

