{% set data = load_setup_py_data() %}

package:
    name: sharppy
    version: 1.4.0 #{{ data['version'] }}

source:
    git_url: https://github.com/sharppy/SHARPpy.git
    git_rev: andover

extra:
    channels:
     - conda-forge
 
build:
    osx_is_app: True
    entry_points: 
     - sharppy = runsharp.__main__:main

requirements:
    build:
     - setuptools
     - python >=3.4
     - pyside
    run:
     - python >=3.4
     - numpy 
     - pyside

test:
    imports:
     - sharppy

about:
    home: 
    summary:
    license: BSD
    license_file: LICENSE.md
 
