name: testenv
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.6
  - pyside=1.2.*
  - numpy
  - matplotlib
  - pyinstaller
  - conda-build
  - anaconda-client
  - sphinx
  - sphinx-gallery
  - pytest
  - pip:
    - sphinx-prompt  
